### ISSUE TITLE
can not resolve reference

### ISSUE THREAD

**Issue by vinySan** [juanroman/openpay-xamarin#2]
i can't implement openpay-Xamarin, i use the new versión of Xamarin.forms  3.4.0.1008 and 
an error appears

Can not resolve reference: `Openpay.Xamarin`, referenced by `residencialp`. Please add a NuGet package or assembly reference for `Openpay.Xamarin`, or remove the reference to `residencialp`.	residencialp.Android

**Comment by juanroman** [comment]
Reviewing the issue

**Comment by juanroman** [comment]
Please update to latest version: 1.0.25.3 has been rebuilt to prevent this issue. Also, the samples project has been updated to reflect this update.

**Comment by vinySan** [comment]
it works thanks!!!!!
